# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='matricule',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nombre_place',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_ligne',
            field=models.IntegerField(),
        ),
    ]
